//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apadrinamientos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apadrinamientos()
        {
            this.PagosApadrinamiento = new HashSet<PagosApadrinamiento>();
        }
    
        public int ApadrinamientoId { get; set; }
        public int MascotaId { get; set; }
        public int UsuarioId { get; set; }
        public decimal MontoMensual { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string Estado { get; set; }
        public string MetodoPagoPreferido { get; set; }
        public Nullable<int> DiaCobroMensual { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Mascotas Mascotas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagosApadrinamiento> PagosApadrinamiento { get; set; }
    }
}
