//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApoyosEmpresariales
    {
        public int ApoyoId { get; set; }
        public string NombreEmpresa { get; set; }
        public string RUC { get; set; }
        public string ContactoNombre { get; set; }
        public string ContactoEmail { get; set; }
        public string ContactoTelefono { get; set; }
        public string TipoApoyo { get; set; }
        public string DescripcionApoyo { get; set; }
        public Nullable<decimal> MontoValor { get; set; }
        public string Frecuencia { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string Estado { get; set; }
        public string Observaciones { get; set; }
    }
}
