//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditoriaAcciones
    {
        public int AuditoriaId { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public string Accion { get; set; }
        public string Modulo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaAccion { get; set; }
        public string DireccionIP { get; set; }
        public string Detalles { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
