//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaniaAdopcion
    {
        public int IdCampania { get; set; }
        public string NombreCampania { get; set; }
        public string Lugar { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string Actividades { get; set; }
        public byte[] Foto { get; set; }
        public bool Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    }
}
