//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratoAdopcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContratoAdopcion()
        {
            this.SeguimientoAdopcion = new HashSet<SeguimientoAdopcion>();
        }
    
        public int ContratoId { get; set; }
        public int SolicitudId { get; set; }
        public string NumeroContrato { get; set; }
        public Nullable<System.DateTime> FechaContrato { get; set; }
        public string AdoptanteNombre { get; set; }
        public string AdoptanteCedula { get; set; }
        public string AdoptanteDireccion { get; set; }
        public string AdoptanteTelefono { get; set; }
        public string RepresentanteRefugioNombre { get; set; }
        public string RepresentanteRefugioCedula { get; set; }
        public string MascotaNombre { get; set; }
        public string MascotaEspecie { get; set; }
        public string MascotaMicrochip { get; set; }
        public string TerminosCondiciones { get; set; }
        public string FirmaAdoptante { get; set; }
        public Nullable<System.DateTime> FechaFirmaAdoptante { get; set; }
        public string FirmaRefugio { get; set; }
        public Nullable<System.DateTime> FechaFirmaRefugio { get; set; }
        public string Estado { get; set; }
        public string DocumentoPDF { get; set; }
    
        public virtual SolicitudAdopcion SolicitudAdopcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeguimientoAdopcion> SeguimientoAdopcion { get; set; }
    }
}
