//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donaciones
    {
        public int DonacionId { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public string TipoDonacion { get; set; }
        public decimal Monto { get; set; }
        public string Frecuencia { get; set; }
        public Nullable<System.DateTime> FechaDonacion { get; set; }
        public string MetodoPago { get; set; }
        public string NumeroTransaccion { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> Anonima { get; set; }
        public string Mensaje { get; set; }
        public string ComprobanteElectronico { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
