//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluacionAdopcion
    {
        public int EvaluacionId { get; set; }
        public int SolicitudId { get; set; }
        public int EvaluadorId { get; set; }
        public Nullable<System.DateTime> FechaEvaluacion { get; set; }
        public Nullable<int> PuntajeVivienda { get; set; }
        public Nullable<int> PuntajeExperiencia { get; set; }
        public Nullable<int> PuntajeDisponibilidad { get; set; }
        public Nullable<int> PuntajeReferencias { get; set; }
        public Nullable<int> PuntajeCompromiso { get; set; }
        public Nullable<int> PuntajeTotal { get; set; }
        public string Resultado { get; set; }
        public string Observaciones { get; set; }
        public string Recomendaciones { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual SolicitudAdopcion SolicitudAdopcion { get; set; }
    }
}
