//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormularioAdopcionDetalle
    {
        public int FormularioId { get; set; }
        public int SolicitudId { get; set; }
        public string TipoVivienda { get; set; }
        public Nullable<bool> ViviendaPropia { get; set; }
        public Nullable<bool> TieneJardin { get; set; }
        public string TamanioJardin { get; set; }
        public Nullable<bool> PermisoMascotas { get; set; }
        public Nullable<bool> ExperienciaPreviaConMascotas { get; set; }
        public string DetalleExperiencia { get; set; }
        public Nullable<bool> TieneMascotasActualmente { get; set; }
        public Nullable<int> CantidadPerros { get; set; }
        public Nullable<int> CantidadGatos { get; set; }
        public string OtrasMascotas { get; set; }
        public Nullable<bool> MascotasEsterilizadas { get; set; }
        public string TiempoDisponibleDiario { get; set; }
        public Nullable<int> PersonasEnCasa { get; set; }
        public Nullable<bool> HayNinios { get; set; }
        public string EdadesNinios { get; set; }
        public string QuienCuidaraMascota { get; set; }
        public bool AceptaEsterilizacion { get; set; }
        public bool AceptaVisitasSeguimiento { get; set; }
        public bool AceptaCondicionesLOBA { get; set; }
        public bool AceptaDevolucionSiNoPuedeAtender { get; set; }
        public string MotivoAdopcion { get; set; }
        public string QuePasaSiCambiaResidencia { get; set; }
        public string QuePasaSiProblemasComportamiento { get; set; }
        public string VeterinarioReferencia { get; set; }
        public string ReferenciaPersonal1 { get; set; }
        public string TelefonoReferencia1 { get; set; }
        public string ReferenciaPersonal2 { get; set; }
        public string TelefonoReferencia2 { get; set; }
        public Nullable<System.DateTime> FechaLlenado { get; set; }
    
        public virtual SolicitudAdopcion SolicitudAdopcion { get; set; }
    }
}
