//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialEstadosMascota
    {
        public int HistorialId { get; set; }
        public int MascotaId { get; set; }
        public string EstadoAnterior { get; set; }
        public string EstadoNuevo { get; set; }
        public string Motivo { get; set; }
        public Nullable<System.DateTime> FechaCambio { get; set; }
        public int UsuarioId { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Mascotas Mascotas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
