//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialMedico
    {
        public int HistorialId { get; set; }
        public int MascotaId { get; set; }
        public int VeterinarioId { get; set; }
        public Nullable<System.DateTime> FechaConsulta { get; set; }
        public string TipoConsulta { get; set; }
        public string Diagnostico { get; set; }
        public string Tratamiento { get; set; }
        public string Observaciones { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> Temperatura { get; set; }
        public string EstadoGeneral { get; set; }
        public Nullable<System.DateTime> ProximaConsulta { get; set; }
        public string DocumentoAdjunto { get; set; }
    
        public virtual Mascotas Mascotas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
