//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorasVoluntariado
    {
        public int HorasId { get; set; }
        public int UsuarioId { get; set; }
        public Nullable<int> ActividadId { get; set; }
        public System.DateTime FechaActividad { get; set; }
        public decimal HorasTrabajadas { get; set; }
        public string TipoActividad { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> ValidadoPor { get; set; }
        public Nullable<System.DateTime> FechaValidacion { get; set; }
    
        public virtual Actividades Actividades { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
    }
}
