//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenesAdicionales
    {
        public int ImagenId { get; set; }
        public string EntidadTipo { get; set; }
        public int EntidadId { get; set; }
        public string PathImagen { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<System.DateTime> FechaSubida { get; set; }
        public Nullable<int> SubidaPor { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
