//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InscripcionesActividades
    {
        public int InscripcionId { get; set; }
        public int ActividadId { get; set; }
        public int UsuarioId { get; set; }
        public Nullable<System.DateTime> FechaInscripcion { get; set; }
        public string Estado { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Actividades Actividades { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
