//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mascotas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mascotas()
        {
            this.Apadrinamientos = new HashSet<Apadrinamientos>();
            this.HistorialMedico = new HashSet<HistorialMedico>();
            this.MascotaVacunas = new HashSet<MascotaVacunas>();
            this.ReportesRescate = new HashSet<ReportesRescate>();
            this.SolicitudAdopcion = new HashSet<SolicitudAdopcion>();
            this.Tratamientos = new HashSet<Tratamientos>();
        }
    
        public int MascotaId { get; set; }
        public string Nombre { get; set; }
        public string Especie { get; set; }
        public string Raza { get; set; }
        public string Sexo { get; set; }
        public string EdadAproximada { get; set; }
        public string Tamanio { get; set; }
        public string Color { get; set; }
        public string Categoria { get; set; }
        public string TipoEspecial { get; set; }
        public string Estado { get; set; }
        public string DescripcionGeneral { get; set; }
        public string CaracteristicasComportamiento { get; set; }
        public string HistoriaRescate { get; set; }
        public byte[] ImagenPrincipal { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaDisponible { get; set; }
        public Nullable<System.DateTime> FechaAdopcion { get; set; }
        public Nullable<int> RescatistaId { get; set; }
        public Nullable<int> VeterinarioAsignado { get; set; }
        public Nullable<bool> Esterilizado { get; set; }
        public string Microchip { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apadrinamientos> Apadrinamientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialMedico> HistorialMedico { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MascotaVacunas> MascotaVacunas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportesRescate> ReportesRescate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudAdopcion> SolicitudAdopcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tratamientos> Tratamientos { get; set; }
    }
}
