//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MascotaVacunas
    {
        public int MascotaVacunaId { get; set; }
        public int MascotaId { get; set; }
        public int VacunaId { get; set; }
        public System.DateTime FechaAplicacion { get; set; }
        public int VeterinarioId { get; set; }
        public Nullable<System.DateTime> ProximaDosis { get; set; }
        public string Lote { get; set; }
        public string Laboratorio { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Mascotas Mascotas { get; set; }
        public virtual Vacunas Vacunas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
