//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MascotasPerdidas
    {
        public int MascotaPerdidaId { get; set; }
        public int UsuarioPropietario { get; set; }
        public string NombreMascota { get; set; }
        public string Especie { get; set; }
        public string Raza { get; set; }
        public string Sexo { get; set; }
        public string Edad { get; set; }
        public string Color { get; set; }
        public string CaracteristicasDistintivas { get; set; }
        public System.DateTime FechaPerdida { get; set; }
        public string UbicacionPerdida { get; set; }
        public byte[] ImagenMascota { get; set; }
        public string ContactoNombre { get; set; }
        public string ContactoTelefono { get; set; }
        public string ContactoEmail { get; set; }
        public Nullable<decimal> Recompensa { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaEncontrada { get; set; }
        public Nullable<System.DateTime> FechaPublicacion { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
