//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientosContables
    {
        public int MovimientoId { get; set; }
        public string TipoMovimiento { get; set; }
        public string Categoria { get; set; }
        public string Concepto { get; set; }
        public decimal Monto { get; set; }
        public Nullable<System.DateTime> FechaMovimiento { get; set; }
        public string MetodoPago { get; set; }
        public string NumeroComprobante { get; set; }
        public Nullable<int> ReferenciaId { get; set; }
        public string TipoReferencia { get; set; }
        public int ResponsableRegistro { get; set; }
        public string Observaciones { get; set; }
        public string ComprobanteAdjunto { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
