//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagosApadrinamiento
    {
        public int PagoId { get; set; }
        public int ApadrinamientoId { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public decimal Monto { get; set; }
        public string MesPagado { get; set; }
        public string MetodoPago { get; set; }
        public string NumeroTransaccion { get; set; }
        public string Estado { get; set; }
        public string ComprobanteElectronico { get; set; }
    
        public virtual Apadrinamientos Apadrinamientos { get; set; }
    }
}
