//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedidos()
        {
            this.PedidoDetalle = new HashSet<PedidoDetalle>();
        }
    
        public int PedidoId { get; set; }
        public int UsuarioId { get; set; }
        public string NumeroPedido { get; set; }
        public Nullable<System.DateTime> FechaPedido { get; set; }
        public string Estado { get; set; }
        public decimal SubTotal { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public decimal Total { get; set; }
        public string MetodoPago { get; set; }
        public string EstadoPago { get; set; }
        public string DireccionEntrega { get; set; }
        public string CiudadEntrega { get; set; }
        public string TelefonoEntrega { get; set; }
        public string ReferenciaEntrega { get; set; }
        public Nullable<System.DateTime> FechaEntregaEstimada { get; set; }
        public Nullable<System.DateTime> FechaEntregaReal { get; set; }
        public string Observaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoDetalle> PedidoDetalle { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
