//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.PedidoDetalle = new HashSet<PedidoDetalle>();
        }
    
        public int ProductoId { get; set; }
        public int CategoriaId { get; set; }
        public string NombreProducto { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> StockMinimo { get; set; }
        public byte[] ImagenPrincipal { get; set; }
        public string SKU { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<bool> Destacado { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual CategoriasProducto CategoriasProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoDetalle> PedidoDetalle { get; set; }
    }
}
