//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RefugioMascotasDBEntities : DbContext
    {
        public RefugioMascotasDBEntities()
            : base("name=RefugioMascotasDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actividades> Actividades { get; set; }
        public virtual DbSet<Apadrinamientos> Apadrinamientos { get; set; }
        public virtual DbSet<ApoyosEmpresariales> ApoyosEmpresariales { get; set; }
        public virtual DbSet<AuditoriaAcciones> AuditoriaAcciones { get; set; }
        public virtual DbSet<CategoriasProducto> CategoriasProducto { get; set; }
        public virtual DbSet<ConfiguracionSistema> ConfiguracionSistema { get; set; }
        public virtual DbSet<ContratoAdopcion> ContratoAdopcion { get; set; }
        public virtual DbSet<Donaciones> Donaciones { get; set; }
        public virtual DbSet<EvaluacionAdopcion> EvaluacionAdopcion { get; set; }
        public virtual DbSet<FormularioAdopcionDetalle> FormularioAdopcionDetalle { get; set; }
        public virtual DbSet<HistorialMedico> HistorialMedico { get; set; }
        public virtual DbSet<HorasVoluntariado> HorasVoluntariado { get; set; }
        public virtual DbSet<ImagenesAdicionales> ImagenesAdicionales { get; set; }
        public virtual DbSet<InscripcionesActividades> InscripcionesActividades { get; set; }
        public virtual DbSet<Mascotas> Mascotas { get; set; }
        public virtual DbSet<MascotasPerdidas> MascotasPerdidas { get; set; }
        public virtual DbSet<MascotaVacunas> MascotaVacunas { get; set; }
        public virtual DbSet<MovimientosContables> MovimientosContables { get; set; }
        public virtual DbSet<PagosApadrinamiento> PagosApadrinamiento { get; set; }
        public virtual DbSet<PedidoDetalle> PedidoDetalle { get; set; }
        public virtual DbSet<Pedidos> Pedidos { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<ReportesRescate> ReportesRescate { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SeguimientoAdopcion> SeguimientoAdopcion { get; set; }
        public virtual DbSet<SolicitudAdopcion> SolicitudAdopcion { get; set; }
        public virtual DbSet<Tratamientos> Tratamientos { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<UsuariosRoles> UsuariosRoles { get; set; }
        public virtual DbSet<Vacunas> Vacunas { get; set; }
        public virtual DbSet<vw_BalanceContable> vw_BalanceContable { get; set; }
        public virtual DbSet<vw_MascotasDisponibles> vw_MascotasDisponibles { get; set; }
        public virtual DbSet<vw_ResumenAdopciones> vw_ResumenAdopciones { get; set; }
        public virtual DbSet<CampaniaAdopcion> CampaniaAdopcion { get; set; }
        public virtual DbSet<RefugioAdopcion> RefugioAdopcion { get; set; }
        public virtual DbSet<RolPermisos> RolPermisos { get; set; }
        public virtual DbSet<HistorialEstadosMascota> HistorialEstadosMascota { get; set; }
    
        public virtual int sp_ArchivarMascota(Nullable<int> mascotaId, Nullable<int> usuarioId, string motivo, ObjectParameter resultado)
        {
            var mascotaIdParameter = mascotaId.HasValue ?
                new ObjectParameter("MascotaId", mascotaId) :
                new ObjectParameter("MascotaId", typeof(int));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var motivoParameter = motivo != null ?
                new ObjectParameter("Motivo", motivo) :
                new ObjectParameter("Motivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ArchivarMascota", mascotaIdParameter, usuarioIdParameter, motivoParameter, resultado);
        }
    
        public virtual int sp_RestaurarMascota(Nullable<int> mascotaId, Nullable<int> usuarioId, string nuevoEstado, string motivo, ObjectParameter resultado)
        {
            var mascotaIdParameter = mascotaId.HasValue ?
                new ObjectParameter("MascotaId", mascotaId) :
                new ObjectParameter("MascotaId", typeof(int));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var nuevoEstadoParameter = nuevoEstado != null ?
                new ObjectParameter("NuevoEstado", nuevoEstado) :
                new ObjectParameter("NuevoEstado", typeof(string));
    
            var motivoParameter = motivo != null ?
                new ObjectParameter("Motivo", motivo) :
                new ObjectParameter("Motivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RestaurarMascota", mascotaIdParameter, usuarioIdParameter, nuevoEstadoParameter, motivoParameter, resultado);
        }
    }
}
