//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefugioAdopcion
    {
        public int IdRefugio { get; set; }
        public string NombreRefugio { get; set; }
        public string Contacto { get; set; }
        public string Direccion { get; set; }
        public string PersonaEncargada { get; set; }
        public bool Estado { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<int> Capacidad { get; set; }
        public Nullable<int> MascotasActuales { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
    }
}
