//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportesRescate
    {
        public int ReporteId { get; set; }
        public Nullable<int> UsuarioReportante { get; set; }
        public string NombreReportante { get; set; }
        public string TelefonoReportante { get; set; }
        public string EmailReportante { get; set; }
        public Nullable<System.DateTime> FechaReporte { get; set; }
        public string UbicacionReporte { get; set; }
        public string CoordenadasGPS { get; set; }
        public string TipoAnimal { get; set; }
        public string DescripcionAnimal { get; set; }
        public string CondicionAnimal { get; set; }
        public string DescripcionSituacion { get; set; }
        public string Urgencia { get; set; }
        public string Estado { get; set; }
        public Nullable<int> RescatistaAsignado { get; set; }
        public Nullable<System.DateTime> FechaRescate { get; set; }
        public Nullable<int> MascotaRescatadaId { get; set; }
        public string ObservacionesSeguimiento { get; set; }
    
        public virtual Mascotas Mascotas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
    }
}
