//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolPermisos
    {
        public int RolPermisoId { get; set; }
        public int RolId { get; set; }
        public string Permiso { get; set; }
        public Nullable<System.DateTime> FechaAsignacion { get; set; }
        public Nullable<int> AsignadoPor { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
