//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeguimientoAdopcion
    {
        public int SeguimientoId { get; set; }
        public int ContratoId { get; set; }
        public Nullable<System.DateTime> FechaSeguimiento { get; set; }
        public string TipoSeguimiento { get; set; }
        public int ResponsableSeguimiento { get; set; }
        public string EstadoMascota { get; set; }
        public string CondicionesVivienda { get; set; }
        public string RelacionConAdoptante { get; set; }
        public string Observaciones { get; set; }
        public string Recomendaciones { get; set; }
        public Nullable<bool> RequiereIntervencion { get; set; }
        public Nullable<System.DateTime> ProximoSeguimiento { get; set; }
        public string FotosEvidencia { get; set; }
    
        public virtual ContratoAdopcion ContratoAdopcion { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
