//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudAdopcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SolicitudAdopcion()
        {
            this.ContratoAdopcion = new HashSet<ContratoAdopcion>();
            this.EvaluacionAdopcion = new HashSet<EvaluacionAdopcion>();
            this.FormularioAdopcionDetalle = new HashSet<FormularioAdopcionDetalle>();
        }
    
        public int SolicitudId { get; set; }
        public int MascotaId { get; set; }
        public int UsuarioId { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public string Estado { get; set; }
        public Nullable<int> PuntajeEvaluacion { get; set; }
        public string ResultadoEvaluacion { get; set; }
        public Nullable<System.DateTime> FechaEvaluacion { get; set; }
        public Nullable<int> EvaluadoPor { get; set; }
        public string MotivoRechazo { get; set; }
        public Nullable<System.DateTime> FechaRespuesta { get; set; }
        public string Observaciones { get; set; }
        public string EstadoAdopcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoAdopcion> ContratoAdopcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionAdopcion> EvaluacionAdopcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormularioAdopcionDetalle> FormularioAdopcionDetalle { get; set; }
        public virtual Mascotas Mascotas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
    }
}
