//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tratamientos
    {
        public int TratamientoId { get; set; }
        public int MascotaId { get; set; }
        public int VeterinarioId { get; set; }
        public string NombreTratamiento { get; set; }
        public string Descripcion { get; set; }
        public string Medicamentos { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string Estado { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Mascotas Mascotas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
