//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Actividades = new HashSet<Actividades>();
            this.Apadrinamientos = new HashSet<Apadrinamientos>();
            this.AuditoriaAcciones = new HashSet<AuditoriaAcciones>();
            this.ConfiguracionSistema = new HashSet<ConfiguracionSistema>();
            this.Donaciones = new HashSet<Donaciones>();
            this.EvaluacionAdopcion = new HashSet<EvaluacionAdopcion>();
            this.HistorialMedico = new HashSet<HistorialMedico>();
            this.HorasVoluntariado = new HashSet<HorasVoluntariado>();
            this.HorasVoluntariado1 = new HashSet<HorasVoluntariado>();
            this.ImagenesAdicionales = new HashSet<ImagenesAdicionales>();
            this.InscripcionesActividades = new HashSet<InscripcionesActividades>();
            this.Mascotas = new HashSet<Mascotas>();
            this.Mascotas1 = new HashSet<Mascotas>();
            this.MascotasPerdidas = new HashSet<MascotasPerdidas>();
            this.MascotaVacunas = new HashSet<MascotaVacunas>();
            this.MovimientosContables = new HashSet<MovimientosContables>();
            this.Pedidos = new HashSet<Pedidos>();
            this.ReportesRescate = new HashSet<ReportesRescate>();
            this.ReportesRescate1 = new HashSet<ReportesRescate>();
            this.SeguimientoAdopcion = new HashSet<SeguimientoAdopcion>();
            this.SolicitudAdopcion = new HashSet<SolicitudAdopcion>();
            this.SolicitudAdopcion1 = new HashSet<SolicitudAdopcion>();
            this.Tratamientos = new HashSet<Tratamientos>();
            this.UsuariosRoles = new HashSet<UsuariosRoles>();
            this.UsuariosRoles1 = new HashSet<UsuariosRoles>();
            this.RolPermisos = new HashSet<RolPermisos>();
            this.HistorialEstadosMascota = new HashSet<HistorialEstadosMascota>();
        }
    
        public int UsuarioId { get; set; }
        public string NombreCompleto { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Cedula { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public string Provincia { get; set; }
        public string PasswordHash { get; set; }
        public string Salt { get; set; }
        public byte[] ImagenPerfil { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> UltimoAcceso { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<bool> EmailConfirmado { get; set; }
        public Nullable<bool> TelefonoConfirmado { get; set; }
        public Nullable<System.DateTime> FechaUltimoCambioPassword { get; set; }
        public Nullable<int> IntentosFallidos { get; set; }
        public Nullable<System.DateTime> FechaBloqueoTemporal { get; set; }
        public Nullable<System.DateTime> FechaDesbloqueo { get; set; }
        public Nullable<bool> BloqueadoPermanentemente { get; set; }
        public Nullable<System.DateTime> FechaUltimoIntentoFallido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actividades> Actividades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apadrinamientos> Apadrinamientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditoriaAcciones> AuditoriaAcciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfiguracionSistema> ConfiguracionSistema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donaciones> Donaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionAdopcion> EvaluacionAdopcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialMedico> HistorialMedico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorasVoluntariado> HorasVoluntariado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorasVoluntariado> HorasVoluntariado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImagenesAdicionales> ImagenesAdicionales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InscripcionesActividades> InscripcionesActividades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mascotas> Mascotas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mascotas> Mascotas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MascotasPerdidas> MascotasPerdidas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MascotaVacunas> MascotaVacunas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientosContables> MovimientosContables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportesRescate> ReportesRescate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportesRescate> ReportesRescate1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeguimientoAdopcion> SeguimientoAdopcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudAdopcion> SolicitudAdopcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudAdopcion> SolicitudAdopcion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tratamientos> Tratamientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuariosRoles> UsuariosRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuariosRoles> UsuariosRoles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolPermisos> RolPermisos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialEstadosMascota> HistorialEstadosMascota { get; set; }
    }
}
