//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacunas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vacunas()
        {
            this.MascotaVacunas = new HashSet<MascotaVacunas>();
        }
    
        public int VacunaId { get; set; }
        public string NombreVacuna { get; set; }
        public string Descripcion { get; set; }
        public string EspecieAplicable { get; set; }
        public string EdadRecomendada { get; set; }
        public string FrecuenciaRefuerzo { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MascotaVacunas> MascotaVacunas { get; set; }
    }
}
