//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMASCOTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ResumenAdopciones
    {
        public int SolicitudId { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public string Estado { get; set; }
        public string MascotaNombre { get; set; }
        public string Especie { get; set; }
        public string AdoptanteNombre { get; set; }
        public string AdoptanteEmail { get; set; }
        public string AdoptanteTelefono { get; set; }
        public Nullable<int> PuntajeEvaluacion { get; set; }
        public string ResultadoEvaluacion { get; set; }
    }
}
